// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rtapi/realtime.proto

/*
Package rtapi is a generated protocol buffer package.

It is generated from these files:
	rtapi/realtime.proto

It has these top-level messages:
	Envelope
	Error
	Match
	MatchCreate
	MatchData
	MatchDataSend
	MatchJoin
	MatchLeave
	MatchPresenceEvent
	MatchmakerAdd
	MatchmakerMatched
	MatchmakerRemove
	MatchmakerTicket
	Notifications
	Stream
	StreamData
	StreamPresence
	StreamPresenceEvent
*/
package rtapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"
import nakama_api "github.com/heroiclabs/nakama/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The selection of possible error codes.
type Error_Code int32

const (
	// An unexpected result from the server.
	Error_RUNTIME_EXCEPTION Error_Code = 0
	// The server received a message which is not recognised.
	Error_UNRECOGNIZED_PAYLOAD Error_Code = 1
	// A message was expected but contains no content.
	Error_MISSING_PAYLOAD Error_Code = 2
	// Fields in the message have an invalid format.
	Error_BAD_INPUT Error_Code = 3
	// The match id was not found.
	Error_MATCH_NOT_FOUND Error_Code = 4
	// The match join was rejected.
	Error_MATCH_JOIN_REJECTED Error_Code = 5
	// The runtime function does not exist on the server.
	Error_RUNTIME_FUNCTION_NOT_FOUND Error_Code = 6
	// The runtime function executed with an error.
	Error_RUNTIME_FUNCTION_EXCEPTION Error_Code = 7
)

var Error_Code_name = map[int32]string{
	0: "RUNTIME_EXCEPTION",
	1: "UNRECOGNIZED_PAYLOAD",
	2: "MISSING_PAYLOAD",
	3: "BAD_INPUT",
	4: "MATCH_NOT_FOUND",
	5: "MATCH_JOIN_REJECTED",
	6: "RUNTIME_FUNCTION_NOT_FOUND",
	7: "RUNTIME_FUNCTION_EXCEPTION",
}
var Error_Code_value = map[string]int32{
	"RUNTIME_EXCEPTION":          0,
	"UNRECOGNIZED_PAYLOAD":       1,
	"MISSING_PAYLOAD":            2,
	"BAD_INPUT":                  3,
	"MATCH_NOT_FOUND":            4,
	"MATCH_JOIN_REJECTED":        5,
	"RUNTIME_FUNCTION_NOT_FOUND": 6,
	"RUNTIME_FUNCTION_EXCEPTION": 7,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}
func (Error_Code) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// An envelope for a realtime message.
type Envelope struct {
	Cid string `protobuf:"bytes,1,opt,name=cid" json:"cid,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Envelope_Error
	//	*Envelope_Match
	//	*Envelope_MatchCreate
	//	*Envelope_MatchData
	//	*Envelope_MatchDataSend
	//	*Envelope_MatchJoin
	//	*Envelope_MatchLeave
	//	*Envelope_MatchPresenceEvent
	//	*Envelope_MatchmakerAdd
	//	*Envelope_MatchmakerMatched
	//	*Envelope_MatchmakerRemove
	//	*Envelope_MatchmakerTicket
	//	*Envelope_Notifications
	//	*Envelope_Rpc
	//	*Envelope_StreamData
	//	*Envelope_StreamPresenceEvent
	Message isEnvelope_Message `protobuf_oneof:"message"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}
type Envelope_Match struct {
	Match *Match `protobuf:"bytes,3,opt,name=match,oneof"`
}
type Envelope_MatchCreate struct {
	MatchCreate *MatchCreate `protobuf:"bytes,4,opt,name=match_create,json=matchCreate,oneof"`
}
type Envelope_MatchData struct {
	MatchData *MatchData `protobuf:"bytes,5,opt,name=match_data,json=matchData,oneof"`
}
type Envelope_MatchDataSend struct {
	MatchDataSend *MatchDataSend `protobuf:"bytes,6,opt,name=match_data_send,json=matchDataSend,oneof"`
}
type Envelope_MatchJoin struct {
	MatchJoin *MatchJoin `protobuf:"bytes,7,opt,name=match_join,json=matchJoin,oneof"`
}
type Envelope_MatchLeave struct {
	MatchLeave *MatchLeave `protobuf:"bytes,8,opt,name=match_leave,json=matchLeave,oneof"`
}
type Envelope_MatchPresenceEvent struct {
	MatchPresenceEvent *MatchPresenceEvent `protobuf:"bytes,9,opt,name=match_presence_event,json=matchPresenceEvent,oneof"`
}
type Envelope_MatchmakerAdd struct {
	MatchmakerAdd *MatchmakerAdd `protobuf:"bytes,10,opt,name=matchmaker_add,json=matchmakerAdd,oneof"`
}
type Envelope_MatchmakerMatched struct {
	MatchmakerMatched *MatchmakerMatched `protobuf:"bytes,11,opt,name=matchmaker_matched,json=matchmakerMatched,oneof"`
}
type Envelope_MatchmakerRemove struct {
	MatchmakerRemove *MatchmakerRemove `protobuf:"bytes,12,opt,name=matchmaker_remove,json=matchmakerRemove,oneof"`
}
type Envelope_MatchmakerTicket struct {
	MatchmakerTicket *MatchmakerTicket `protobuf:"bytes,13,opt,name=matchmaker_ticket,json=matchmakerTicket,oneof"`
}
type Envelope_Notifications struct {
	Notifications *Notifications `protobuf:"bytes,14,opt,name=notifications,oneof"`
}
type Envelope_Rpc struct {
	Rpc *nakama_api.Rpc `protobuf:"bytes,15,opt,name=rpc,oneof"`
}
type Envelope_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,16,opt,name=stream_data,json=streamData,oneof"`
}
type Envelope_StreamPresenceEvent struct {
	StreamPresenceEvent *StreamPresenceEvent `protobuf:"bytes,17,opt,name=stream_presence_event,json=streamPresenceEvent,oneof"`
}

func (*Envelope_Error) isEnvelope_Message()               {}
func (*Envelope_Match) isEnvelope_Message()               {}
func (*Envelope_MatchCreate) isEnvelope_Message()         {}
func (*Envelope_MatchData) isEnvelope_Message()           {}
func (*Envelope_MatchDataSend) isEnvelope_Message()       {}
func (*Envelope_MatchJoin) isEnvelope_Message()           {}
func (*Envelope_MatchLeave) isEnvelope_Message()          {}
func (*Envelope_MatchPresenceEvent) isEnvelope_Message()  {}
func (*Envelope_MatchmakerAdd) isEnvelope_Message()       {}
func (*Envelope_MatchmakerMatched) isEnvelope_Message()   {}
func (*Envelope_MatchmakerRemove) isEnvelope_Message()    {}
func (*Envelope_MatchmakerTicket) isEnvelope_Message()    {}
func (*Envelope_Notifications) isEnvelope_Message()       {}
func (*Envelope_Rpc) isEnvelope_Message()                 {}
func (*Envelope_StreamData) isEnvelope_Message()          {}
func (*Envelope_StreamPresenceEvent) isEnvelope_Message() {}

func (m *Envelope) GetMessage() isEnvelope_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Envelope) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Envelope) GetError() *Error {
	if x, ok := m.GetMessage().(*Envelope_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Envelope) GetMatch() *Match {
	if x, ok := m.GetMessage().(*Envelope_Match); ok {
		return x.Match
	}
	return nil
}

func (m *Envelope) GetMatchCreate() *MatchCreate {
	if x, ok := m.GetMessage().(*Envelope_MatchCreate); ok {
		return x.MatchCreate
	}
	return nil
}

func (m *Envelope) GetMatchData() *MatchData {
	if x, ok := m.GetMessage().(*Envelope_MatchData); ok {
		return x.MatchData
	}
	return nil
}

func (m *Envelope) GetMatchDataSend() *MatchDataSend {
	if x, ok := m.GetMessage().(*Envelope_MatchDataSend); ok {
		return x.MatchDataSend
	}
	return nil
}

func (m *Envelope) GetMatchJoin() *MatchJoin {
	if x, ok := m.GetMessage().(*Envelope_MatchJoin); ok {
		return x.MatchJoin
	}
	return nil
}

func (m *Envelope) GetMatchLeave() *MatchLeave {
	if x, ok := m.GetMessage().(*Envelope_MatchLeave); ok {
		return x.MatchLeave
	}
	return nil
}

func (m *Envelope) GetMatchPresenceEvent() *MatchPresenceEvent {
	if x, ok := m.GetMessage().(*Envelope_MatchPresenceEvent); ok {
		return x.MatchPresenceEvent
	}
	return nil
}

func (m *Envelope) GetMatchmakerAdd() *MatchmakerAdd {
	if x, ok := m.GetMessage().(*Envelope_MatchmakerAdd); ok {
		return x.MatchmakerAdd
	}
	return nil
}

func (m *Envelope) GetMatchmakerMatched() *MatchmakerMatched {
	if x, ok := m.GetMessage().(*Envelope_MatchmakerMatched); ok {
		return x.MatchmakerMatched
	}
	return nil
}

func (m *Envelope) GetMatchmakerRemove() *MatchmakerRemove {
	if x, ok := m.GetMessage().(*Envelope_MatchmakerRemove); ok {
		return x.MatchmakerRemove
	}
	return nil
}

func (m *Envelope) GetMatchmakerTicket() *MatchmakerTicket {
	if x, ok := m.GetMessage().(*Envelope_MatchmakerTicket); ok {
		return x.MatchmakerTicket
	}
	return nil
}

func (m *Envelope) GetNotifications() *Notifications {
	if x, ok := m.GetMessage().(*Envelope_Notifications); ok {
		return x.Notifications
	}
	return nil
}

func (m *Envelope) GetRpc() *nakama_api.Rpc {
	if x, ok := m.GetMessage().(*Envelope_Rpc); ok {
		return x.Rpc
	}
	return nil
}

func (m *Envelope) GetStreamData() *StreamData {
	if x, ok := m.GetMessage().(*Envelope_StreamData); ok {
		return x.StreamData
	}
	return nil
}

func (m *Envelope) GetStreamPresenceEvent() *StreamPresenceEvent {
	if x, ok := m.GetMessage().(*Envelope_StreamPresenceEvent); ok {
		return x.StreamPresenceEvent
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Envelope) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Envelope_OneofMarshaler, _Envelope_OneofUnmarshaler, _Envelope_OneofSizer, []interface{}{
		(*Envelope_Error)(nil),
		(*Envelope_Match)(nil),
		(*Envelope_MatchCreate)(nil),
		(*Envelope_MatchData)(nil),
		(*Envelope_MatchDataSend)(nil),
		(*Envelope_MatchJoin)(nil),
		(*Envelope_MatchLeave)(nil),
		(*Envelope_MatchPresenceEvent)(nil),
		(*Envelope_MatchmakerAdd)(nil),
		(*Envelope_MatchmakerMatched)(nil),
		(*Envelope_MatchmakerRemove)(nil),
		(*Envelope_MatchmakerTicket)(nil),
		(*Envelope_Notifications)(nil),
		(*Envelope_Rpc)(nil),
		(*Envelope_StreamData)(nil),
		(*Envelope_StreamPresenceEvent)(nil),
	}
}

func _Envelope_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Envelope)
	// message
	switch x := m.Message.(type) {
	case *Envelope_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *Envelope_Match:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Match); err != nil {
			return err
		}
	case *Envelope_MatchCreate:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchCreate); err != nil {
			return err
		}
	case *Envelope_MatchData:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchData); err != nil {
			return err
		}
	case *Envelope_MatchDataSend:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchDataSend); err != nil {
			return err
		}
	case *Envelope_MatchJoin:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchJoin); err != nil {
			return err
		}
	case *Envelope_MatchLeave:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchLeave); err != nil {
			return err
		}
	case *Envelope_MatchPresenceEvent:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchPresenceEvent); err != nil {
			return err
		}
	case *Envelope_MatchmakerAdd:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchmakerAdd); err != nil {
			return err
		}
	case *Envelope_MatchmakerMatched:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchmakerMatched); err != nil {
			return err
		}
	case *Envelope_MatchmakerRemove:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchmakerRemove); err != nil {
			return err
		}
	case *Envelope_MatchmakerTicket:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MatchmakerTicket); err != nil {
			return err
		}
	case *Envelope_Notifications:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Notifications); err != nil {
			return err
		}
	case *Envelope_Rpc:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Rpc); err != nil {
			return err
		}
	case *Envelope_StreamData:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StreamData); err != nil {
			return err
		}
	case *Envelope_StreamPresenceEvent:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StreamPresenceEvent); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Envelope.Message has unexpected type %T", x)
	}
	return nil
}

func _Envelope_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Envelope)
	switch tag {
	case 2: // message.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_Error{msg}
		return true, err
	case 3: // message.match
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Match)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_Match{msg}
		return true, err
	case 4: // message.match_create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchCreate)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchCreate{msg}
		return true, err
	case 5: // message.match_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchData)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchData{msg}
		return true, err
	case 6: // message.match_data_send
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchDataSend)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchDataSend{msg}
		return true, err
	case 7: // message.match_join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchJoin)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchJoin{msg}
		return true, err
	case 8: // message.match_leave
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchLeave)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchLeave{msg}
		return true, err
	case 9: // message.match_presence_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchPresenceEvent)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchPresenceEvent{msg}
		return true, err
	case 10: // message.matchmaker_add
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchmakerAdd)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchmakerAdd{msg}
		return true, err
	case 11: // message.matchmaker_matched
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchmakerMatched)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchmakerMatched{msg}
		return true, err
	case 12: // message.matchmaker_remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchmakerRemove)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchmakerRemove{msg}
		return true, err
	case 13: // message.matchmaker_ticket
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MatchmakerTicket)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_MatchmakerTicket{msg}
		return true, err
	case 14: // message.notifications
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Notifications)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_Notifications{msg}
		return true, err
	case 15: // message.rpc
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(nakama_api.Rpc)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_Rpc{msg}
		return true, err
	case 16: // message.stream_data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamData)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_StreamData{msg}
		return true, err
	case 17: // message.stream_presence_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamPresenceEvent)
		err := b.DecodeMessage(msg)
		m.Message = &Envelope_StreamPresenceEvent{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Envelope_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Envelope)
	// message
	switch x := m.Message.(type) {
	case *Envelope_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_Match:
		s := proto.Size(x.Match)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchCreate:
		s := proto.Size(x.MatchCreate)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchData:
		s := proto.Size(x.MatchData)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchDataSend:
		s := proto.Size(x.MatchDataSend)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchJoin:
		s := proto.Size(x.MatchJoin)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchLeave:
		s := proto.Size(x.MatchLeave)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchPresenceEvent:
		s := proto.Size(x.MatchPresenceEvent)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchmakerAdd:
		s := proto.Size(x.MatchmakerAdd)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchmakerMatched:
		s := proto.Size(x.MatchmakerMatched)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchmakerRemove:
		s := proto.Size(x.MatchmakerRemove)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_MatchmakerTicket:
		s := proto.Size(x.MatchmakerTicket)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_Notifications:
		s := proto.Size(x.Notifications)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_Rpc:
		s := proto.Size(x.Rpc)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_StreamData:
		s := proto.Size(x.StreamData)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Envelope_StreamPresenceEvent:
		s := proto.Size(x.StreamPresenceEvent)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A logical error which may occur on the server.
type Error struct {
	// The error code which should be one of "Error.Code" enums.
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// A message in English to help developers debug the response.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// Additional error details which may be different for each response.
	Context map[string]string `protobuf:"bytes,3,rep,name=context" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

// A realtime match.
type Match struct {
	// The match unique ID.
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	// True if it's an server-managed authoritative match, false otherwise.
	Authoritative bool `protobuf:"varint,2,opt,name=authoritative" json:"authoritative,omitempty"`
	// Match label, if any.
	Label *google_protobuf.StringValue `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	// The number of users currently in the match.
	Size int32 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	// The users currently in the match.
	Presences []*StreamPresence `protobuf:"bytes,5,rep,name=presences" json:"presences,omitempty"`
	// A reference to the current user's presence in the match.
	Self *StreamPresence `protobuf:"bytes,6,opt,name=self" json:"self,omitempty"`
}

func (m *Match) Reset()                    { *m = Match{} }
func (m *Match) String() string            { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()               {}
func (*Match) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Match) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func (m *Match) GetAuthoritative() bool {
	if m != nil {
		return m.Authoritative
	}
	return false
}

func (m *Match) GetLabel() *google_protobuf.StringValue {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Match) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Match) GetPresences() []*StreamPresence {
	if m != nil {
		return m.Presences
	}
	return nil
}

func (m *Match) GetSelf() *StreamPresence {
	if m != nil {
		return m.Self
	}
	return nil
}

// Create a new realtime match.
type MatchCreate struct {
}

func (m *MatchCreate) Reset()                    { *m = MatchCreate{} }
func (m *MatchCreate) String() string            { return proto.CompactTextString(m) }
func (*MatchCreate) ProtoMessage()               {}
func (*MatchCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Realtime match data received from the server.
type MatchData struct {
	// The match unique ID.
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	// A reference to the user presence that sent this data, if any.
	Presence *StreamPresence `protobuf:"bytes,2,opt,name=presence" json:"presence,omitempty"`
	// Op code value.
	OpCode int64 `protobuf:"varint,3,opt,name=op_code,json=opCode" json:"op_code,omitempty"`
	// Data payload, if any.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MatchData) Reset()                    { *m = MatchData{} }
func (m *MatchData) String() string            { return proto.CompactTextString(m) }
func (*MatchData) ProtoMessage()               {}
func (*MatchData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MatchData) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func (m *MatchData) GetPresence() *StreamPresence {
	if m != nil {
		return m.Presence
	}
	return nil
}

func (m *MatchData) GetOpCode() int64 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *MatchData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Send realtime match data to the server.
type MatchDataSend struct {
	// The match unique ID.
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	// Op code value.
	OpCode int64 `protobuf:"varint,2,opt,name=op_code,json=opCode" json:"op_code,omitempty"`
	// Data payload, if any.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// List of presences in the match to deliver to, if filtering is required. Otherwise deliver to everyone in the match.
	Presences []*StreamPresence `protobuf:"bytes,4,rep,name=presences" json:"presences,omitempty"`
}

func (m *MatchDataSend) Reset()                    { *m = MatchDataSend{} }
func (m *MatchDataSend) String() string            { return proto.CompactTextString(m) }
func (*MatchDataSend) ProtoMessage()               {}
func (*MatchDataSend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MatchDataSend) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func (m *MatchDataSend) GetOpCode() int64 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *MatchDataSend) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MatchDataSend) GetPresences() []*StreamPresence {
	if m != nil {
		return m.Presences
	}
	return nil
}

// Join an existing realtime match.
type MatchJoin struct {
	// Types that are valid to be assigned to Id:
	//	*MatchJoin_MatchId
	//	*MatchJoin_Token
	Id isMatchJoin_Id `protobuf_oneof:"id"`
}

func (m *MatchJoin) Reset()                    { *m = MatchJoin{} }
func (m *MatchJoin) String() string            { return proto.CompactTextString(m) }
func (*MatchJoin) ProtoMessage()               {}
func (*MatchJoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isMatchJoin_Id interface {
	isMatchJoin_Id()
}

type MatchJoin_MatchId struct {
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,oneof"`
}
type MatchJoin_Token struct {
	Token string `protobuf:"bytes,2,opt,name=token,oneof"`
}

func (*MatchJoin_MatchId) isMatchJoin_Id() {}
func (*MatchJoin_Token) isMatchJoin_Id()   {}

func (m *MatchJoin) GetId() isMatchJoin_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *MatchJoin) GetMatchId() string {
	if x, ok := m.GetId().(*MatchJoin_MatchId); ok {
		return x.MatchId
	}
	return ""
}

func (m *MatchJoin) GetToken() string {
	if x, ok := m.GetId().(*MatchJoin_Token); ok {
		return x.Token
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MatchJoin) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MatchJoin_OneofMarshaler, _MatchJoin_OneofUnmarshaler, _MatchJoin_OneofSizer, []interface{}{
		(*MatchJoin_MatchId)(nil),
		(*MatchJoin_Token)(nil),
	}
}

func _MatchJoin_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MatchJoin)
	// id
	switch x := m.Id.(type) {
	case *MatchJoin_MatchId:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.MatchId)
	case *MatchJoin_Token:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Token)
	case nil:
	default:
		return fmt.Errorf("MatchJoin.Id has unexpected type %T", x)
	}
	return nil
}

func _MatchJoin_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MatchJoin)
	switch tag {
	case 1: // id.match_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Id = &MatchJoin_MatchId{x}
		return true, err
	case 2: // id.token
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Id = &MatchJoin_Token{x}
		return true, err
	default:
		return false, nil
	}
}

func _MatchJoin_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MatchJoin)
	// id
	switch x := m.Id.(type) {
	case *MatchJoin_MatchId:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.MatchId)))
		n += len(x.MatchId)
	case *MatchJoin_Token:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Token)))
		n += len(x.Token)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Leave a realtime match.
type MatchLeave struct {
	// The match unique ID.
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
}

func (m *MatchLeave) Reset()                    { *m = MatchLeave{} }
func (m *MatchLeave) String() string            { return proto.CompactTextString(m) }
func (*MatchLeave) ProtoMessage()               {}
func (*MatchLeave) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MatchLeave) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

// A set of joins and leaves on a particular realtime match.
type MatchPresenceEvent struct {
	// The match unique ID.
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	// User presences that have just joined the match.
	Joins []*StreamPresence `protobuf:"bytes,2,rep,name=joins" json:"joins,omitempty"`
	// User presences that have just left the match.
	Leaves []*StreamPresence `protobuf:"bytes,3,rep,name=leaves" json:"leaves,omitempty"`
}

func (m *MatchPresenceEvent) Reset()                    { *m = MatchPresenceEvent{} }
func (m *MatchPresenceEvent) String() string            { return proto.CompactTextString(m) }
func (*MatchPresenceEvent) ProtoMessage()               {}
func (*MatchPresenceEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MatchPresenceEvent) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func (m *MatchPresenceEvent) GetJoins() []*StreamPresence {
	if m != nil {
		return m.Joins
	}
	return nil
}

func (m *MatchPresenceEvent) GetLeaves() []*StreamPresence {
	if m != nil {
		return m.Leaves
	}
	return nil
}

// Start a new matchmaking process.
type MatchmakerAdd struct {
	// Minimum total user count to match together.
	MinCount int32 `protobuf:"varint,1,opt,name=min_count,json=minCount" json:"min_count,omitempty"`
	// Maximum total user count to match together.
	MaxCount int32 `protobuf:"varint,2,opt,name=max_count,json=maxCount" json:"max_count,omitempty"`
	// Filter query used to identify suitable users.
	Filter string `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	// String properties.
	StringProperties map[string]string `protobuf:"bytes,4,rep,name=string_properties,json=stringProperties" json:"string_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Numeric properties.
	NumericProperties map[string]float64 `protobuf:"bytes,5,rep,name=numeric_properties,json=numericProperties" json:"numeric_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *MatchmakerAdd) Reset()                    { *m = MatchmakerAdd{} }
func (m *MatchmakerAdd) String() string            { return proto.CompactTextString(m) }
func (*MatchmakerAdd) ProtoMessage()               {}
func (*MatchmakerAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MatchmakerAdd) GetMinCount() int32 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *MatchmakerAdd) GetMaxCount() int32 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *MatchmakerAdd) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *MatchmakerAdd) GetStringProperties() map[string]string {
	if m != nil {
		return m.StringProperties
	}
	return nil
}

func (m *MatchmakerAdd) GetNumericProperties() map[string]float64 {
	if m != nil {
		return m.NumericProperties
	}
	return nil
}

// A successful matchmaking result.
type MatchmakerMatched struct {
	// The matchmaking ticket that has completed.
	Ticket string `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
	// The match token or match ID to join.
	//
	// Types that are valid to be assigned to Id:
	//	*MatchmakerMatched_MatchId
	//	*MatchmakerMatched_Token
	Id isMatchmakerMatched_Id `protobuf_oneof:"id"`
	// The users that have been matched together, and information about their matchmaking data.
	Users []*MatchmakerMatched_MatchmakerUser `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
	// A reference to the current user and their properties.
	Self *MatchmakerMatched_MatchmakerUser `protobuf:"bytes,5,opt,name=self" json:"self,omitempty"`
}

func (m *MatchmakerMatched) Reset()                    { *m = MatchmakerMatched{} }
func (m *MatchmakerMatched) String() string            { return proto.CompactTextString(m) }
func (*MatchmakerMatched) ProtoMessage()               {}
func (*MatchmakerMatched) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type isMatchmakerMatched_Id interface {
	isMatchmakerMatched_Id()
}

type MatchmakerMatched_MatchId struct {
	MatchId string `protobuf:"bytes,2,opt,name=match_id,json=matchId,oneof"`
}
type MatchmakerMatched_Token struct {
	Token string `protobuf:"bytes,3,opt,name=token,oneof"`
}

func (*MatchmakerMatched_MatchId) isMatchmakerMatched_Id() {}
func (*MatchmakerMatched_Token) isMatchmakerMatched_Id()   {}

func (m *MatchmakerMatched) GetId() isMatchmakerMatched_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *MatchmakerMatched) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *MatchmakerMatched) GetMatchId() string {
	if x, ok := m.GetId().(*MatchmakerMatched_MatchId); ok {
		return x.MatchId
	}
	return ""
}

func (m *MatchmakerMatched) GetToken() string {
	if x, ok := m.GetId().(*MatchmakerMatched_Token); ok {
		return x.Token
	}
	return ""
}

func (m *MatchmakerMatched) GetUsers() []*MatchmakerMatched_MatchmakerUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MatchmakerMatched) GetSelf() *MatchmakerMatched_MatchmakerUser {
	if m != nil {
		return m.Self
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MatchmakerMatched) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MatchmakerMatched_OneofMarshaler, _MatchmakerMatched_OneofUnmarshaler, _MatchmakerMatched_OneofSizer, []interface{}{
		(*MatchmakerMatched_MatchId)(nil),
		(*MatchmakerMatched_Token)(nil),
	}
}

func _MatchmakerMatched_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MatchmakerMatched)
	// id
	switch x := m.Id.(type) {
	case *MatchmakerMatched_MatchId:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.MatchId)
	case *MatchmakerMatched_Token:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Token)
	case nil:
	default:
		return fmt.Errorf("MatchmakerMatched.Id has unexpected type %T", x)
	}
	return nil
}

func _MatchmakerMatched_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MatchmakerMatched)
	switch tag {
	case 2: // id.match_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Id = &MatchmakerMatched_MatchId{x}
		return true, err
	case 3: // id.token
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Id = &MatchmakerMatched_Token{x}
		return true, err
	default:
		return false, nil
	}
}

func _MatchmakerMatched_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MatchmakerMatched)
	// id
	switch x := m.Id.(type) {
	case *MatchmakerMatched_MatchId:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.MatchId)))
		n += len(x.MatchId)
	case *MatchmakerMatched_Token:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Token)))
		n += len(x.Token)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MatchmakerMatched_MatchmakerUser struct {
	// User info.
	Presence *StreamPresence `protobuf:"bytes,1,opt,name=presence" json:"presence,omitempty"`
	// String properties.
	StringProperties map[string]string `protobuf:"bytes,5,rep,name=string_properties,json=stringProperties" json:"string_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Numeric properties.
	NumericProperties map[string]float64 `protobuf:"bytes,6,rep,name=numeric_properties,json=numericProperties" json:"numeric_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *MatchmakerMatched_MatchmakerUser) Reset()         { *m = MatchmakerMatched_MatchmakerUser{} }
func (m *MatchmakerMatched_MatchmakerUser) String() string { return proto.CompactTextString(m) }
func (*MatchmakerMatched_MatchmakerUser) ProtoMessage()    {}
func (*MatchmakerMatched_MatchmakerUser) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

func (m *MatchmakerMatched_MatchmakerUser) GetPresence() *StreamPresence {
	if m != nil {
		return m.Presence
	}
	return nil
}

func (m *MatchmakerMatched_MatchmakerUser) GetStringProperties() map[string]string {
	if m != nil {
		return m.StringProperties
	}
	return nil
}

func (m *MatchmakerMatched_MatchmakerUser) GetNumericProperties() map[string]float64 {
	if m != nil {
		return m.NumericProperties
	}
	return nil
}

// Cancel an existing ongoing matchmaking process.
type MatchmakerRemove struct {
	// The ticket to cancel.
	Ticket string `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
}

func (m *MatchmakerRemove) Reset()                    { *m = MatchmakerRemove{} }
func (m *MatchmakerRemove) String() string            { return proto.CompactTextString(m) }
func (*MatchmakerRemove) ProtoMessage()               {}
func (*MatchmakerRemove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MatchmakerRemove) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

// A ticket representing a new matchmaking process.
type MatchmakerTicket struct {
	// The ticket that can be used to cancel matchmaking.
	Ticket string `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
}

func (m *MatchmakerTicket) Reset()                    { *m = MatchmakerTicket{} }
func (m *MatchmakerTicket) String() string            { return proto.CompactTextString(m) }
func (*MatchmakerTicket) ProtoMessage()               {}
func (*MatchmakerTicket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MatchmakerTicket) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

// A collection of zero or more notifications.
type Notifications struct {
	// Collection of notifications.
	Notifications []*nakama_api.Notification `protobuf:"bytes,1,rep,name=notifications" json:"notifications,omitempty"`
}

func (m *Notifications) Reset()                    { *m = Notifications{} }
func (m *Notifications) String() string            { return proto.CompactTextString(m) }
func (*Notifications) ProtoMessage()               {}
func (*Notifications) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Notifications) GetNotifications() []*nakama_api.Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

// Represents identifying information for a stream.
type Stream struct {
	// Mode identifies the type of stream.
	Mode int32 `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	// Subject is the primary identifier, if any.
	Subject string `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	// Descriptor is a secondary identifier, if any.
	Descriptor_ string `protobuf:"bytes,3,opt,name=descriptor" json:"descriptor,omitempty"`
	// The label is an arbitrary identifying string, if the stream has one.
	Label string `protobuf:"bytes,4,opt,name=label" json:"label,omitempty"`
}

func (m *Stream) Reset()                    { *m = Stream{} }
func (m *Stream) String() string            { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()               {}
func (*Stream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Stream) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Stream) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Stream) GetDescriptor_() string {
	if m != nil {
		return m.Descriptor_
	}
	return ""
}

func (m *Stream) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

// A data message delivered over a stream.
type StreamData struct {
	// The stream this data message relates to.
	Stream *Stream `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	// The sender, if any.
	Sender *StreamPresence `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	// Arbitrary contents of the data message.
	Data string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *StreamData) Reset()                    { *m = StreamData{} }
func (m *StreamData) String() string            { return proto.CompactTextString(m) }
func (*StreamData) ProtoMessage()               {}
func (*StreamData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *StreamData) GetStream() *Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *StreamData) GetSender() *StreamPresence {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *StreamData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// A user session associated to a stream, usually through a list operation or a join/leave event.
type StreamPresence struct {
	// The user this presence belongs to.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// A unique session ID identifying the particular connection, because the user may have many.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// The username for display purposes.
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	// Whether this presence generates persistent data/messages, if applicable for the stream type.
	Persistence bool `protobuf:"varint,4,opt,name=persistence" json:"persistence,omitempty"`
	// A user-set status message for this stream, if applicable.
	Status string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *StreamPresence) Reset()                    { *m = StreamPresence{} }
func (m *StreamPresence) String() string            { return proto.CompactTextString(m) }
func (*StreamPresence) ProtoMessage()               {}
func (*StreamPresence) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *StreamPresence) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StreamPresence) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *StreamPresence) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *StreamPresence) GetPersistence() bool {
	if m != nil {
		return m.Persistence
	}
	return false
}

func (m *StreamPresence) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// A set of joins and leaves on a particular stream.
type StreamPresenceEvent struct {
	// The stream this event relates to.
	Stream *Stream `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	// Presences joining the stream as part of this event, if any.
	Joins []*StreamPresence `protobuf:"bytes,2,rep,name=joins" json:"joins,omitempty"`
	// Presences leaving the stream as part of this event, if any.
	Leaves []*StreamPresence `protobuf:"bytes,3,rep,name=leaves" json:"leaves,omitempty"`
}

func (m *StreamPresenceEvent) Reset()                    { *m = StreamPresenceEvent{} }
func (m *StreamPresenceEvent) String() string            { return proto.CompactTextString(m) }
func (*StreamPresenceEvent) ProtoMessage()               {}
func (*StreamPresenceEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *StreamPresenceEvent) GetStream() *Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *StreamPresenceEvent) GetJoins() []*StreamPresence {
	if m != nil {
		return m.Joins
	}
	return nil
}

func (m *StreamPresenceEvent) GetLeaves() []*StreamPresence {
	if m != nil {
		return m.Leaves
	}
	return nil
}

func init() {
	proto.RegisterType((*Envelope)(nil), "nakama.realtime.Envelope")
	proto.RegisterType((*Error)(nil), "nakama.realtime.Error")
	proto.RegisterType((*Match)(nil), "nakama.realtime.Match")
	proto.RegisterType((*MatchCreate)(nil), "nakama.realtime.MatchCreate")
	proto.RegisterType((*MatchData)(nil), "nakama.realtime.MatchData")
	proto.RegisterType((*MatchDataSend)(nil), "nakama.realtime.MatchDataSend")
	proto.RegisterType((*MatchJoin)(nil), "nakama.realtime.MatchJoin")
	proto.RegisterType((*MatchLeave)(nil), "nakama.realtime.MatchLeave")
	proto.RegisterType((*MatchPresenceEvent)(nil), "nakama.realtime.MatchPresenceEvent")
	proto.RegisterType((*MatchmakerAdd)(nil), "nakama.realtime.MatchmakerAdd")
	proto.RegisterType((*MatchmakerMatched)(nil), "nakama.realtime.MatchmakerMatched")
	proto.RegisterType((*MatchmakerMatched_MatchmakerUser)(nil), "nakama.realtime.MatchmakerMatched.MatchmakerUser")
	proto.RegisterType((*MatchmakerRemove)(nil), "nakama.realtime.MatchmakerRemove")
	proto.RegisterType((*MatchmakerTicket)(nil), "nakama.realtime.MatchmakerTicket")
	proto.RegisterType((*Notifications)(nil), "nakama.realtime.Notifications")
	proto.RegisterType((*Stream)(nil), "nakama.realtime.Stream")
	proto.RegisterType((*StreamData)(nil), "nakama.realtime.StreamData")
	proto.RegisterType((*StreamPresence)(nil), "nakama.realtime.StreamPresence")
	proto.RegisterType((*StreamPresenceEvent)(nil), "nakama.realtime.StreamPresenceEvent")
	proto.RegisterEnum("nakama.realtime.Error_Code", Error_Code_name, Error_Code_value)
}

func init() { proto.RegisterFile("rtapi/realtime.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xbd, 0x6f, 0x1b, 0xc7,
	0x12, 0xe7, 0x91, 0x3c, 0x8a, 0x1c, 0x89, 0x12, 0xb5, 0xfa, 0xf0, 0x3d, 0xda, 0x4f, 0x4f, 0xef,
	0x6c, 0xe0, 0x19, 0x2e, 0x28, 0x3c, 0x3b, 0x46, 0x02, 0x1b, 0x36, 0x22, 0x51, 0x94, 0x48, 0xc7,
	0xa2, 0x88, 0x95, 0x94, 0x0f, 0x37, 0x87, 0xd5, 0xdd, 0x4a, 0x3a, 0x8b, 0xf7, 0x81, 0xbb, 0xa5,
	0x6c, 0xa7, 0x4e, 0x95, 0x2a, 0x55, 0xca, 0x04, 0x48, 0x99, 0x3e, 0xa9, 0xd3, 0x05, 0xf9, 0x77,
	0x52, 0xa7, 0x08, 0xf6, 0xe3, 0xc8, 0x23, 0xc5, 0x0f, 0x2b, 0x45, 0x80, 0x54, 0xda, 0x99, 0xfd,
	0xcd, 0x6f, 0xe7, 0x66, 0x67, 0x67, 0x46, 0x84, 0xd5, 0x88, 0x91, 0xd0, 0xdd, 0x8a, 0x28, 0xe9,
	0x32, 0xd7, 0xa3, 0xb5, 0x30, 0x0a, 0x58, 0x80, 0x96, 0x7c, 0x72, 0x49, 0x3c, 0x52, 0x4b, 0xd4,
	0xd5, 0x8d, 0xf3, 0x20, 0x38, 0xef, 0xd2, 0x2d, 0xb1, 0x7d, 0xda, 0x3b, 0xdb, 0x7a, 0x13, 0x91,
	0x30, 0xa4, 0x51, 0x2c, 0x0d, 0xaa, 0x0f, 0xce, 0x5d, 0x76, 0xd1, 0x3b, 0xad, 0xd9, 0x81, 0xb7,
	0x75, 0x41, 0xa3, 0xc0, 0xb5, 0xbb, 0xe4, 0x34, 0xde, 0x92, 0x34, 0x5b, 0xfc, 0x04, 0x12, 0xba,
	0x12, 0x6b, 0xfe, 0x5e, 0x84, 0x62, 0xc3, 0xbf, 0xa2, 0xdd, 0x20, 0xa4, 0xa8, 0x02, 0x39, 0xdb,
	0x75, 0x0c, 0x6d, 0x53, 0xbb, 0x5f, 0xc2, 0x7c, 0x89, 0x6a, 0xa0, 0xd3, 0x28, 0x0a, 0x22, 0x23,
	0xbb, 0xa9, 0xdd, 0x9f, 0x7f, 0xb8, 0x5e, 0x1b, 0xf1, 0xa5, 0xd6, 0xe0, 0xbb, 0xcd, 0x0c, 0x96,
	0x30, 0x8e, 0xf7, 0x08, 0xb3, 0x2f, 0x8c, 0xdc, 0x04, 0xfc, 0x01, 0xdf, 0xe5, 0x78, 0x01, 0x43,
	0xdb, 0xb0, 0x20, 0x16, 0x96, 0x1d, 0x51, 0xc2, 0xa8, 0x91, 0x17, 0x66, 0x77, 0xc6, 0x9b, 0xd5,
	0x05, 0xa6, 0x99, 0xc1, 0xf3, 0xde, 0x40, 0x44, 0x4f, 0x01, 0x24, 0x85, 0x43, 0x18, 0x31, 0x74,
	0x41, 0x50, 0x1d, 0x4f, 0xb0, 0x4b, 0x18, 0x69, 0x66, 0x70, 0xc9, 0x4b, 0x04, 0xd4, 0x84, 0xa5,
	0x81, 0xb1, 0x15, 0x53, 0xdf, 0x31, 0x0a, 0x82, 0x61, 0x63, 0x32, 0xc3, 0x11, 0xf5, 0x9d, 0x66,
	0x06, 0x97, 0xbd, 0xb4, 0x62, 0xe0, 0xc6, 0xeb, 0xc0, 0xf5, 0x8d, 0xb9, 0x69, 0x6e, 0xbc, 0x08,
	0x5c, 0xbf, 0xef, 0x06, 0x17, 0xd0, 0x73, 0x90, 0x9f, 0x64, 0x75, 0x29, 0xb9, 0xa2, 0x46, 0x51,
	0x58, 0xdf, 0x1e, 0x6f, 0xfd, 0x92, 0x43, 0x9a, 0x19, 0x2c, 0x8f, 0x13, 0x12, 0xfa, 0x0c, 0x56,
	0xa5, 0x7d, 0x18, 0xd1, 0x98, 0xfa, 0x36, 0xb5, 0xe8, 0x15, 0xf5, 0x99, 0x51, 0x12, 0x44, 0x77,
	0xc7, 0x13, 0x75, 0x14, 0xb6, 0xc1, 0xa1, 0xcd, 0x0c, 0x46, 0xde, 0x35, 0x2d, 0xda, 0x87, 0x45,
	0xa1, 0xf5, 0xc8, 0x25, 0x8d, 0x2c, 0xe2, 0x38, 0x06, 0x4c, 0x0b, 0x8f, 0x80, 0x6d, 0x3b, 0x83,
	0xf0, 0x24, 0x0a, 0x74, 0x04, 0x28, 0x45, 0x24, 0x96, 0xd4, 0x31, 0xe6, 0x05, 0x99, 0x39, 0x85,
	0xec, 0x40, 0x22, 0x9b, 0x19, 0xbc, 0xec, 0x8d, 0x2a, 0x51, 0x07, 0x52, 0x4a, 0x2b, 0xa2, 0x5e,
	0x70, 0x45, 0x8d, 0x05, 0xc1, 0xf9, 0xdf, 0x29, 0x9c, 0x58, 0x00, 0x9b, 0x19, 0x5c, 0xf1, 0x46,
	0x74, 0x23, 0x8c, 0xcc, 0xb5, 0x2f, 0x29, 0x33, 0xca, 0x33, 0x19, 0x8f, 0x05, 0x70, 0x98, 0x51,
	0xea, 0xd0, 0x1e, 0x94, 0xfd, 0x80, 0xb9, 0x67, 0xae, 0x4d, 0x98, 0x1b, 0xf8, 0xb1, 0xb1, 0x38,
	0x21, 0x80, 0xed, 0x34, 0x8a, 0x07, 0x70, 0xc8, 0x0c, 0xdd, 0x85, 0x5c, 0x14, 0xda, 0xc6, 0x92,
	0xb0, 0x5e, 0x4a, 0xac, 0xf9, 0x43, 0xc6, 0xa1, 0xdd, 0xcc, 0x60, 0xbe, 0xcb, 0xf3, 0x28, 0x66,
	0x11, 0x25, 0x9e, 0x7c, 0x0c, 0x95, 0x09, 0x79, 0x74, 0x24, 0x30, 0xea, 0x35, 0x40, 0xdc, 0x97,
	0xd0, 0x2b, 0x58, 0x53, 0xf6, 0x23, 0x89, 0xb4, 0x2c, 0x98, 0xee, 0x4d, 0x60, 0x1a, 0xcd, 0xa4,
	0x95, 0xf8, 0xba, 0x7a, 0xa7, 0x04, 0x73, 0x1e, 0x8d, 0x63, 0x72, 0x4e, 0xcd, 0x3f, 0xb2, 0xa0,
	0x8b, 0xc2, 0x81, 0x10, 0xe4, 0xed, 0xc0, 0xa1, 0xa2, 0xe4, 0xe8, 0x58, 0xac, 0x91, 0xd1, 0x07,
	0x8a, 0xaa, 0x53, 0xc2, 0x89, 0x88, 0x9e, 0xc1, 0x9c, 0x1d, 0xf8, 0x8c, 0xbe, 0x65, 0x46, 0x6e,
	0x33, 0x37, 0x36, 0xb3, 0x05, 0x6d, 0xad, 0x2e, 0x51, 0x0d, 0x9f, 0x45, 0xef, 0x70, 0x62, 0x53,
	0x7d, 0x02, 0x0b, 0xe9, 0x0d, 0x5e, 0xee, 0x2e, 0xe9, 0xbb, 0xa4, 0xdc, 0x5d, 0xd2, 0x77, 0x68,
	0x15, 0xf4, 0x2b, 0xd2, 0xed, 0x25, 0x07, 0x4b, 0xe1, 0x49, 0xf6, 0x23, 0xcd, 0xfc, 0x4d, 0x83,
	0x7c, 0x9d, 0x7b, 0xb7, 0x06, 0xcb, 0xf8, 0xa4, 0x7d, 0xdc, 0x3a, 0x68, 0x58, 0x8d, 0xcf, 0xeb,
	0x8d, 0xce, 0x71, 0xeb, 0xb0, 0x5d, 0xc9, 0x20, 0x03, 0x56, 0x4f, 0xda, 0xb8, 0x51, 0x3f, 0xdc,
	0x6f, 0xb7, 0x5e, 0x35, 0x76, 0xad, 0xce, 0xf6, 0x17, 0x2f, 0x0f, 0xb7, 0x77, 0x2b, 0x1a, 0x5a,
	0x81, 0xa5, 0x83, 0xd6, 0xd1, 0x51, 0xab, 0xbd, 0xdf, 0x57, 0x66, 0x51, 0x19, 0x4a, 0x3b, 0xdb,
	0xbb, 0x56, 0xab, 0xdd, 0x39, 0x39, 0xae, 0xe4, 0x04, 0x66, 0xfb, 0xb8, 0xde, 0xb4, 0xda, 0x87,
	0xc7, 0xd6, 0xde, 0xe1, 0x49, 0x7b, 0xb7, 0x92, 0x47, 0xb7, 0x60, 0x45, 0x2a, 0x5f, 0x1c, 0xb6,
	0xda, 0x16, 0x6e, 0xbc, 0x68, 0xd4, 0x8f, 0x1b, 0xbb, 0x15, 0x1d, 0x6d, 0x40, 0x35, 0x71, 0x61,
	0xef, 0xa4, 0x5d, 0xe7, 0x1e, 0xa4, 0x0c, 0x0b, 0x63, 0xf7, 0x07, 0xbe, 0xce, 0x99, 0x5f, 0x65,
	0x41, 0x17, 0xb9, 0x8b, 0xfe, 0x05, 0x45, 0x59, 0x37, 0xfa, 0x55, 0x7f, 0x4e, 0xc8, 0x2d, 0x07,
	0xdd, 0x83, 0x32, 0xe9, 0xb1, 0x8b, 0x20, 0x72, 0x19, 0x61, 0xee, 0x95, 0x0c, 0x49, 0x11, 0x0f,
	0x2b, 0xd1, 0x43, 0xd0, 0xbb, 0xe4, 0x94, 0x76, 0x55, 0xbd, 0xbf, 0x53, 0x93, 0xad, 0xa9, 0x96,
	0xb4, 0x26, 0x9e, 0x20, 0xae, 0x7f, 0xfe, 0x29, 0x8f, 0x23, 0x96, 0x50, 0x7e, 0xe7, 0xb1, 0xfb,
	0xa5, 0xac, 0xf5, 0x3a, 0x16, 0x6b, 0xf4, 0x0c, 0x4a, 0x49, 0xc6, 0xc5, 0x86, 0x2e, 0xee, 0xf6,
	0x3f, 0x33, 0x92, 0x0d, 0x0f, 0x2c, 0xd0, 0x23, 0xc8, 0xc7, 0xb4, 0x7b, 0xa6, 0x6a, 0xf7, 0x4c,
	0x4b, 0x01, 0x36, 0xcb, 0x30, 0x9f, 0x6a, 0x2b, 0xe6, 0x37, 0x1a, 0x94, 0xfa, 0x35, 0x7e, 0x5a,
	0x64, 0x9e, 0x42, 0x31, 0x39, 0x59, 0xb5, 0xc5, 0x99, 0x07, 0xf6, 0x0d, 0xd0, 0x2d, 0x98, 0x0b,
	0x42, 0x4b, 0xe4, 0x3c, 0x0f, 0x59, 0x0e, 0x17, 0x82, 0x50, 0xe4, 0x15, 0x82, 0xbc, 0x78, 0xb3,
	0x3c, 0x2a, 0x0b, 0x58, 0xac, 0xcd, 0x6f, 0x35, 0x28, 0x0f, 0xb5, 0x9d, 0x69, 0x6e, 0xa5, 0x98,
	0xb3, 0x63, 0x99, 0x73, 0x03, 0xe6, 0xe1, 0x78, 0xe7, 0x6f, 0x1a, 0x6f, 0x73, 0x4f, 0x85, 0x4a,
	0x34, 0xaf, 0xdb, 0xa3, 0x3e, 0x35, 0x33, 0x03, 0xaf, 0xd6, 0x41, 0x67, 0xc1, 0x25, 0xf5, 0xe5,
	0x8b, 0xe2, 0x8d, 0x5f, 0x88, 0x3b, 0x79, 0xc8, 0xba, 0x8e, 0xf9, 0x3f, 0x80, 0x41, 0x4f, 0x9b,
	0xf2, 0x71, 0xe6, 0xf7, 0x1a, 0xa0, 0xeb, 0x4d, 0x6b, 0x5a, 0x38, 0x1e, 0x83, 0xce, 0x3b, 0x71,
	0x6c, 0x64, 0xdf, 0xef, 0xeb, 0x24, 0x1a, 0x7d, 0x08, 0x05, 0xd1, 0x83, 0x63, 0x55, 0x61, 0x66,
	0xda, 0x29, 0xb8, 0xf9, 0x53, 0x4e, 0xdd, 0x55, 0xbf, 0xe5, 0xdd, 0x86, 0x92, 0xe7, 0xfa, 0x96,
	0x1d, 0xf4, 0x7c, 0xa6, 0x0a, 0x5c, 0xd1, 0x73, 0xfd, 0x3a, 0x97, 0xc5, 0x26, 0x79, 0xab, 0x36,
	0xb3, 0x6a, 0x93, 0xbc, 0x95, 0x9b, 0xeb, 0x50, 0x38, 0x73, 0xbb, 0x8c, 0x46, 0xe2, 0xce, 0x4a,
	0x58, 0x49, 0x88, 0xc0, 0x72, 0x2c, 0xde, 0x93, 0x15, 0x46, 0x41, 0x48, 0x23, 0xe6, 0xf6, 0x6f,
	0xef, 0x83, 0xe9, 0x0d, 0x59, 0xbd, 0xc3, 0x4e, 0xdf, 0x4c, 0x96, 0xc6, 0x4a, 0x3c, 0xa2, 0x46,
	0x0e, 0x20, 0xbf, 0xe7, 0xd1, 0xc8, 0xb5, 0xd3, 0x67, 0xc8, 0x17, 0xf9, 0x78, 0xc6, 0x19, 0x6d,
	0x69, 0x38, 0x7a, 0xc8, 0xb2, 0x3f, 0xaa, 0xaf, 0xd6, 0x61, 0x6d, 0xac, 0x43, 0x37, 0x29, 0xc9,
	0xd5, 0x5d, 0x58, 0x1f, 0x7f, 0xe2, 0x2c, 0x16, 0x2d, 0x5d, 0xd8, 0x7f, 0xd1, 0x61, 0xf9, 0xda,
	0xb8, 0xc1, 0x6f, 0x40, 0x35, 0x7f, 0x49, 0xa2, 0xa4, 0xa1, 0x5c, 0xcf, 0x4e, 0xcc, 0xf5, 0xdc,
	0x50, 0xae, 0xa3, 0x7d, 0xd0, 0x7b, 0x31, 0x8d, 0x92, 0xab, 0xfa, 0xff, 0xec, 0x71, 0x27, 0xa5,
	0x39, 0x89, 0x69, 0x84, 0xa5, 0x3d, 0x6a, 0xa8, 0x32, 0x27, 0x87, 0xdc, 0xbf, 0xc0, 0x23, 0xcc,
	0xab, 0xbf, 0xe6, 0x60, 0x71, 0x78, 0x63, 0xa8, 0xa6, 0x69, 0x37, 0xad, 0x69, 0x6c, 0x5c, 0x5a,
	0xca, 0x94, 0xd9, 0xbf, 0xb1, 0x8f, 0xef, 0x9d, 0xa9, 0x6f, 0xc6, 0x66, 0x6a, 0x41, 0x1c, 0xdb,
	0xbc, 0xf9, 0xb1, 0xff, 0xc4, 0xe4, 0x55, 0x55, 0xf4, 0x01, 0x54, 0x46, 0x87, 0xdb, 0x49, 0x09,
	0x3c, 0x8c, 0x55, 0x23, 0xea, 0x24, 0xec, 0x21, 0x94, 0x87, 0x86, 0x52, 0xf4, 0x7c, 0x74, 0x96,
	0xd5, 0x44, 0xb4, 0x8d, 0xf4, 0x34, 0x9a, 0xb6, 0x18, 0x99, 0x61, 0xcd, 0x2e, 0x14, 0x64, 0x12,
	0xf1, 0x9e, 0xe4, 0xa5, 0xe6, 0x3e, 0x4f, 0xcd, 0x7d, 0x71, 0xef, 0xf4, 0x35, 0xb5, 0x59, 0x32,
	0xf7, 0x29, 0x11, 0x6d, 0x00, 0x38, 0x34, 0xb6, 0x23, 0x37, 0x64, 0x41, 0x52, 0x13, 0x53, 0x1a,
	0x1e, 0x20, 0x39, 0x85, 0xe4, 0x65, 0x98, 0x85, 0x60, 0x7e, 0xad, 0x01, 0x0c, 0x26, 0x5d, 0xb4,
	0x05, 0x05, 0x39, 0x96, 0xaa, 0x04, 0xbf, 0x35, 0x21, 0xc1, 0xb1, 0x82, 0xf1, 0x56, 0xc0, 0xff,
	0x21, 0xa4, 0xd1, 0xfb, 0x76, 0x79, 0x05, 0x1f, 0x6a, 0xb8, 0x25, 0xd5, 0xca, 0xbf, 0xd3, 0x60,
	0x71, 0x18, 0xce, 0x1b, 0x36, 0x7f, 0xd6, 0x83, 0xde, 0x55, 0xe0, 0x62, 0xcb, 0x41, 0xff, 0x06,
	0x88, 0x69, 0x1c, 0xbb, 0x81, 0xdf, 0x2f, 0x33, 0xb8, 0xa4, 0x34, 0x2d, 0x07, 0x55, 0xa1, 0xc8,
	0x81, 0x3e, 0xf1, 0xa8, 0x3a, 0xa2, 0x2f, 0xa3, 0x4d, 0x98, 0x0f, 0x69, 0x14, 0xbb, 0x31, 0x13,
	0x4f, 0x39, 0x2f, 0x66, 0xb6, 0xb4, 0x8a, 0x5f, 0x76, 0xcc, 0x08, 0xeb, 0xc5, 0xa2, 0x8a, 0x94,
	0xb0, 0x92, 0xcc, 0x9f, 0x35, 0x58, 0x19, 0x33, 0xcd, 0xdf, 0x3c, 0x6c, 0x7f, 0x73, 0xe3, 0xdd,
	0xf9, 0x18, 0xd6, 0xec, 0xc0, 0xab, 0x0d, 0x7e, 0xe8, 0x50, 0x86, 0x3b, 0x8b, 0x6d, 0xf1, 0x17,
	0x2b, 0xfb, 0x8e, 0xf6, 0x4a, 0x17, 0xbf, 0xaf, 0xfc, 0x90, 0xcd, 0xb7, 0x3f, 0xe9, 0xec, 0xfc,
	0x98, 0x2d, 0x48, 0xc0, 0x69, 0x41, 0x4c, 0xab, 0x8f, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x33,
	0x07, 0x6b, 0xef, 0x7f, 0x11, 0x00, 0x00,
}
